# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20160923_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guilds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('guild', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Guilds')),
                ('stats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.UserStats')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Guilds'),
        ),
    ]
