# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20160923_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pplList',
            field=models.TextField(null=True),
        ),
    ]
